name: focus-protocol-eeg-analysis
channels:
  - defaults
dependencies:
  - python=3.12
  - ipykernel=6.29.5
  - matplotlib=3.10.0
  - numpy=1.26.4
  - pandas=2.3.1
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - seaborn=0.13.2
  - tensorflow=2.18.1
